
[2016-12-9 14:08:31] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=10&System.Int32=2，
127.0.0.1:16882,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 458
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 442
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 359

[2016-12-9 14:33:28] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=10&System.Int32=2，
127.0.0.1:17346,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 458
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 442
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 359

[2016-12-9 15:21:05] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=10&System.Int32=2，
127.0.0.1:18588,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 458
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 442
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 359

[2016-12-9 15:29:36] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=10&System.Int32=2，
127.0.0.1:18697,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 458
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 442
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 359

[2016-12-9 18:29:13] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=10&System.Int32=2，
127.0.0.1:20694,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 458
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 442
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 359

[2016-12-9 18:29:56] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=10&System.Int32=2，
127.0.0.1:20695,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 458
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 442
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 359

[2016-12-9 18:30:12] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=10&System.Int32=2，
127.0.0.1:20700,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 458
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 442
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 359

[2016-12-9 18:30:56] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=10&System.Int32=2，
127.0.0.1:20706,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 458
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 442
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 359

[2016-12-9 18:31:10] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=10&System.Int32=2，
127.0.0.1:20707,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 458
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 442
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 359

[2016-12-9 18:31:30] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=10&System.Int32=2，
127.0.0.1:20711,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 458
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 442
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 359

[2016/12/17 20:29:50] 处理服务的时候发生异常：
从注册的所有容器中没有找到符合当前类型的提供程序。
System.InvalidOperationException: 从注册的所有容器中没有找到符合当前类型的提供程序。
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 f:\old\PDF.NET.Enterprise\PWMIS.EF\AOPIOC\IOC\Unity.cs:行号 294
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(String serviceName) 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 14
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 338

[2016/12/17 20:43:49] 处理服务的时候发生异常：
从注册的所有容器中没有找到符合当前类型的提供程序。
System.InvalidOperationException: 从注册的所有容器中没有找到符合当前类型的提供程序。
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 f:\old\PDF.NET.Enterprise\PWMIS.EF\AOPIOC\IOC\Unity.cs:行号 294
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(String serviceName) 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 14
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 338

[2016/12/17 20:48:20] 处理服务的时候发生异常：
从注册的所有容器中没有找到符合当前类型的提供程序。
System.InvalidOperationException: 从注册的所有容器中没有找到符合当前类型的提供程序。
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 f:\old\PDF.NET.Enterprise\PWMIS.EF\AOPIOC\IOC\Unity.cs:行号 294
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(String serviceName) 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 14
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 338

[2016/12/17 20:48:41] 处理服务的时候发生异常：
从注册的所有容器中没有找到符合当前类型的提供程序。
System.InvalidOperationException: 从注册的所有容器中没有找到符合当前类型的提供程序。
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 f:\old\PDF.NET.Enterprise\PWMIS.EF\AOPIOC\IOC\Unity.cs:行号 294
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(String serviceName) 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 14
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 338

[2016/12/17 20:50:59] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：从注册的所有容器中没有找到符合当前类型的提供程序。，
请求的Uri:Service:///ServiceFiles/，
127.0.0.1:49592,WMI3501599710

System.InvalidOperationException: 从注册的所有容器中没有找到符合当前类型的提供程序。
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 f:\old\PDF.NET.Enterprise\PWMIS.EF\AOPIOC\IOC\Unity.cs:行号 294
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(String serviceName) 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 14
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 338

[2016/12/17 20:51:22] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：从注册的所有容器中没有找到符合当前类型的提供程序。，
请求的Uri:Service:///ServiceFiles/，
127.0.0.1:49762,WMI3501599710

System.InvalidOperationException: 从注册的所有容器中没有找到符合当前类型的提供程序。
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 f:\old\PDF.NET.Enterprise\PWMIS.EF\AOPIOC\IOC\Unity.cs:行号 294
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(String serviceName) 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 14
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 338

[2016/12/17 20:51:57] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：从注册的所有容器中没有找到符合当前类型的提供程序。，
请求的Uri:Service:///ServiceFiles/，
127.0.0.1:50019,WMI3501599710

System.InvalidOperationException: 从注册的所有容器中没有找到符合当前类型的提供程序。
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 f:\old\PDF.NET.Enterprise\PWMIS.EF\AOPIOC\IOC\Unity.cs:行号 294
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(String serviceName) 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 14
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 338

[2016/12/17 20:52:05] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：从注册的所有容器中没有找到符合当前类型的提供程序。，
请求的Uri:Service:///ServiceFiles/，
127.0.0.1:50119,WMI3501599710

System.InvalidOperationException: 从注册的所有容器中没有找到符合当前类型的提供程序。
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 f:\old\PDF.NET.Enterprise\PWMIS.EF\AOPIOC\IOC\Unity.cs:行号 294
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(String serviceName) 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 14
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 338

[2016/12/17 20:55:31] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：从注册的所有服务提供程序中没有找到当前请求的类型，IService，
请求的Uri:Service:///ServiceFiles/，
127.0.0.1:51411,WMI3501599710

System.InvalidOperationException: 从注册的所有服务提供程序中没有找到当前请求的类型，IService
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 f:\old\PDF.NET.Enterprise\PWMIS.EF\AOPIOC\IOC\Unity.cs:行号 294
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(String serviceName) 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 14
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 338

[2016/12/17 20:57:05] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：从注册的所有服务提供程序中没有找到当前请求的类型，IService，
请求的Uri:Service:///ServiceFiles/，
127.0.0.1:51619,WMI3501599710

System.InvalidOperationException: 从注册的所有服务提供程序中没有找到当前请求的类型，IService
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 f:\old\PDF.NET.Enterprise\PWMIS.EF\AOPIOC\IOC\Unity.cs:行号 294
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(String serviceName) 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 14
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 338

[2016/12/17 20:58:46] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：请求的服务名称不能为空。，
请求的Uri:Service:///ServiceFiles/，
127.0.0.1:52457,WMI3501599710

System.InvalidOperationException: 请求的服务名称不能为空。

[2016/12/17 21:01:46] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：请求的服务名称不能为空。，
请求的Uri:Service:///ServiceFiles/，
127.0.0.1:53502,WMI3501599710

System.InvalidOperationException: 请求的服务名称不能为空。
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 341

[2016/12/17 21:07:25] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：从注册的所有服务提供程序中没有找到当前请求的类型，IService，
请求的Uri:Service://FilesService/ServiceFiles/，
127.0.0.1:55393,WMI3501599710

System.InvalidOperationException: 从注册的所有服务提供程序中没有找到当前请求的类型，IService
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 f:\old\PDF.NET.Enterprise\PWMIS.EF\AOPIOC\IOC\Unity.cs:行号 294
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(String serviceName) 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 14
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 341

[2016/12/17 21:12:57] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：从注册的所有服务提供程序中没有找到当前请求的类型，IService，
请求的Uri:Service://FilesService/ServiceFiles/，
127.0.0.1:57386,WMI3501599710

System.InvalidOperationException: 从注册的所有服务提供程序中没有找到当前请求的类型，IService
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 f:\old\PDF.NET.Enterprise\PWMIS.EF\AOPIOC\IOC\Unity.cs:行号 294
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(String serviceName) 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 14
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 341

[2016/12/17 21:14:08] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：从注册的所有服务提供程序中没有找到当前请求的类型:FilesService，
请求的Uri:Service://FilesService/ServiceFiles/，
127.0.0.1:57897,WMI3501599710

System.InvalidOperationException: 从注册的所有服务提供程序中没有找到当前请求的类型:FilesService
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 f:\old\PDF.NET.Enterprise\PWMIS.EF\AOPIOC\IOC\Unity.cs:行号 294
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(String serviceName) 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 14
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 f:\old\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 341

[2017-1-24 16:42:03] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:47411,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 497
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 481
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\消息服务框架\PDF.NET.Enterprise\PDF.NET.Enterprise\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 393

[2017-4-18 11:14:19] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:36481,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 555
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 539
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-4-18 11:15:32] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:36507,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 555
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 539
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-4-18 13:17:42] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:39138,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 555
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 539
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-4-18 13:22:05] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:39249,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 555
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 539
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-4-18 14:20:56] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:40844,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 555
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 539
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-4-18 14:21:21] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:40845,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 555
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 539
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-4-18 14:28:11] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:41025,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 555
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 539
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-4-18 14:28:47] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:41036,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 555
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 539
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-4-18 15:17:43] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:42241,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 555
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 539
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-4-19 14:11:15] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:59357,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Runtime.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 571
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 555
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 18:03:02] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：未能加载文件或程序集“PWMIS.EnterpriseFramework.Service.Runtime, Version=1.2.4.16, Culture=neutral, PublicKeyToken=null”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:55011,WMI2114256838

System.IO.FileLoadException: 未能加载文件或程序集“PWMIS.EnterpriseFramework.Service.Runtime, Version=1.2.4.16, Culture=neutral, PublicKeyToken=null”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)
文件名:“PWMIS.EnterpriseFramework.Service.Runtime, Version=1.2.4.16, Culture=neutral, PublicKeyToken=null”
   在 System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   在 System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetProviderType(IocProvider provider) 位置 e:\研究\SOD\MessageServiceFramework\AOPIOC\IOC\Unity.cs:行号 144
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetProviderInstance(IocProvider provider) 位置 e:\研究\SOD\MessageServiceFramework\AOPIOC\IOC\Unity.cs:行号 118
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 e:\研究\SOD\MessageServiceFramework\AOPIOC\IOC\Unity.cs:行号 291
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(String serviceName) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 14
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 379

警告: 程序集绑定日志记录被关闭。
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。


[2017-5-8 18:04:02] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:55057,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 18:05:19] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:55092,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 18:05:51] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:55100,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 18:06:16] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:55110,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 18:06:49] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:55124,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 18:07:29] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:55142,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 18:08:16] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:55169,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 19:03:40] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:55906,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 19:05:25] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:55975,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 19:08:38] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:56041,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 19:09:34] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:56063,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 19:10:55] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:56113,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 19:16:33] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:56265,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 19:17:26] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:56300,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 19:18:01] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:56324,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 19:19:20] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:56353,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

[2017-5-8 19:24:51] 处理服务的时候发生异常：
执行服务方法错误，源错误信息：sub error.，
请求的Uri:Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:56476,WMI2114256838

System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 575
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 559
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 408

------------------------------
[2017-05-23 11:10:24]处理服务的时候发生异常：执行服务方法错误：
源错误信息：sub error.，
请求的Uri:
Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:54116,WMI2114256838

错误发生时的异常对象调用堆栈：
System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 e:\研究\SOD\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 33
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 605
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 589
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 435
------------------------------
[2017-06-15 17:17:40]处理服务的时候发生异常：执行服务方法错误：
源错误信息：未能加载文件或程序集“PWMIS.EnterpriseFramework.Service.Runtime, Version=1.2.5.23, Culture=neutral, PublicKeyToken=82fad09ee75ff39d”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)，
请求的Uri:
Publish://TestTimeService/ServerTime/，
127.0.0.1:65511,WMI2114256838

错误发生时的异常对象调用堆栈：
System.IO.FileLoadException: 未能加载文件或程序集“PWMIS.EnterpriseFramework.Service.Runtime, Version=1.2.5.23, Culture=neutral, PublicKeyToken=82fad09ee75ff39d”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)
文件名:“PWMIS.EnterpriseFramework.Service.Runtime, Version=1.2.5.23, Culture=neutral, PublicKeyToken=82fad09ee75ff39d”
   在 System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   在 System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetProviderType(IocProvider provider) 位置 e:\研究\SOD\MessageServiceFramework\AOPIOC\IOC\Unity.cs:行号 144
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetProviderInstance(IocProvider provider) 位置 e:\研究\SOD\MessageServiceFramework\AOPIOC\IOC\Unity.cs:行号 118
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 e:\研究\SOD\MessageServiceFramework\AOPIOC\IOC\Unity.cs:行号 291
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(String serviceName) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 14
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 406

警告: 程序集绑定日志记录被关闭。
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

------------------------------
程序发生未处理的异常：
System.ServiceModel.AddressAlreadyInUseException: 已有针对 IP 终结点 127.0.0.1:8888 的侦听器。如果有其他应用程序已在侦听此终结点，或者，如果在服务主机中具有多个服务终结点，这些终结点具有相同的 IP 终结点但绑定配置不兼容，则可能会发生这种情况。 ---> System.Net.Sockets.SocketException: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Bind(EndPoint localEP)
   在 System.ServiceModel.Channels.SocketConnectionListener.Listen()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ServiceModel.Channels.SocketConnectionListener.Listen()
   在 System.ServiceModel.Channels.ExclusiveTcpTransportManager.OnOpen()
   在 System.ServiceModel.Channels.TransportManager.Open(TransportChannelListener channelListener)
   在 System.ServiceModel.Channels.TransportManagerContainer.Open(SelectTransportManagersCallback selectTransportManagerCallback)
   在 System.ServiceModel.Channels.TransportChannelListener.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.ConnectionOrientedTransportChannelListener.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.TcpChannelListener`2.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.Dispatcher.ChannelDispatcher.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 PWMIS.EnterpriseFramework.Service.Host.Program.Main(String[] args) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceHost\Program.cs:行号 264
------------------------------
程序发生未处理的异常：
System.ServiceModel.AddressAlreadyInUseException: 已有针对 IP 终结点 127.0.0.1:8888 的侦听器。如果有其他应用程序已在侦听此终结点，或者，如果在服务主机中具有多个服务终结点，这些终结点具有相同的 IP 终结点但绑定配置不兼容，则可能会发生这种情况。 ---> System.Net.Sockets.SocketException: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Bind(EndPoint localEP)
   在 System.ServiceModel.Channels.SocketConnectionListener.Listen()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ServiceModel.Channels.SocketConnectionListener.Listen()
   在 System.ServiceModel.Channels.ExclusiveTcpTransportManager.OnOpen()
   在 System.ServiceModel.Channels.TransportManager.Open(TransportChannelListener channelListener)
   在 System.ServiceModel.Channels.TransportManagerContainer.Open(SelectTransportManagersCallback selectTransportManagerCallback)
   在 System.ServiceModel.Channels.TransportChannelListener.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.ConnectionOrientedTransportChannelListener.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.TcpChannelListener`2.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.Dispatcher.ChannelDispatcher.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 PWMIS.EnterpriseFramework.Service.Host.Program.Main(String[] args) 位置 e:\研究\SOD\MessageServiceFramework\PWMISServiceHost\Program.cs:行号 264
------------------------------
[2017-12-18 14:12:03]处理服务的时候发生异常：执行服务方法错误：
源错误信息：sub error.，
请求的Uri:
Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:50500,APIW4Y4VTB7

错误发生时的异常对象调用堆栈：
System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 34
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 657
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2017-12-18 15:17:58]处理服务的时候发生异常：执行服务方法错误：
源错误信息：sub error.，
请求的Uri:
Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:50687,APIW4Y4VTB7

错误发生时的异常对象调用堆栈：
System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 34
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 657
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2017-12-18 16:07:28]处理服务的时候发生异常：执行服务方法错误：
源错误信息：从注册的所有容器中没有找到符合当前类型的提供程序。，
请求的Uri:
Publish://TestTimeService/ServerTime/，
127.0.0.1:50913,APIW4Y4VTB7

错误发生时的异常对象调用堆栈：
System.InvalidOperationException: 从注册的所有容器中没有找到符合当前类型的提供程序。
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 E:\Git\sod\src\MessageServiceFramework\AOPIOC\IOC\Unity.cs:行号 304
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.<>c__DisplayClass1_0.<GetService>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 40
   在 PWMIS.EnterpriseFramework.Service.Runtime.MemoryCacheProvider.Get[T](String cacheKey, Func`1 getData) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\Cache\CacheProvider.cs:行号 58
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(IServiceContext context) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 39
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 445
------------------------------
[2017-12-18 16:09:57]处理服务的时候发生异常：执行服务方法错误：
源错误信息：从注册的所有容器中没有找到符合当前类型的提供程序。，
请求的Uri:
Publish://TestTimeService/ServerTime/，
127.0.0.1:50935,APIW4Y4VTB7

错误发生时的异常对象调用堆栈：
System.InvalidOperationException: 从注册的所有容器中没有找到符合当前类型的提供程序。
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 E:\Git\sod\src\MessageServiceFramework\AOPIOC\IOC\Unity.cs:行号 304
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.<>c__DisplayClass1_0.<GetService>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 40
   在 PWMIS.EnterpriseFramework.Service.Runtime.MemoryCacheProvider.Get[T](String cacheKey, Func`1 getData) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\Cache\CacheProvider.cs:行号 58
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(IServiceContext context) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 39
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 445
------------------------------
[2017-12-18 16:14:10]处理服务的时候发生异常：执行服务方法错误：
源错误信息：从注册的所有容器中没有找到符合当前类型的提供程序。，
请求的Uri:
Publish://TestTimeService/ServerTime/，
127.0.0.1:50953,APIW4Y4VTB7

错误发生时的异常对象调用堆栈：
System.InvalidOperationException: 从注册的所有容器中没有找到符合当前类型的提供程序。
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 E:\Git\sod\src\MessageServiceFramework\AOPIOC\IOC\Unity.cs:行号 304
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.<>c__DisplayClass1_0.<GetService>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 40
   在 PWMIS.EnterpriseFramework.Service.Runtime.MemoryCacheProvider.Get[T](String cacheKey, Func`1 getData) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\Cache\CacheProvider.cs:行号 58
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(IServiceContext context) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 39
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 445
------------------------------
[2017-12-18 16:15:04]处理服务的时候发生异常：执行服务方法错误：
源错误信息：从注册的所有容器中没有找到符合当前类型的提供程序。，
请求的Uri:
Publish://TestTimeService/ServerTime/，
127.0.0.1:50955,APIW4Y4VTB7

错误发生时的异常对象调用堆栈：
System.InvalidOperationException: 从注册的所有容器中没有找到符合当前类型的提供程序。
   在 PWMIS.EnterpriseFramework.IOC.Unity.GetInstance[T](String iocItemKey) 位置 E:\Git\sod\src\MessageServiceFramework\AOPIOC\IOC\Unity.cs:行号 304
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.<>c__DisplayClass1_0.<GetService>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 40
   在 PWMIS.EnterpriseFramework.Service.Runtime.MemoryCacheProvider.Get[T](String cacheKey, Func`1 getData) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\Cache\CacheProvider.cs:行号 58
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceFactory.GetService(IServiceContext context) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceFactory.cs:行号 39
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 445
------------------------------
[2017-12-18 18:17:16]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.ArgumentException: 流不可读。
   在 System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   在 System.IO.StreamReader..ctor(Stream stream)
   在 PWMIS.EnterpriseFramework.Service.Basic.ServiceResponse.GetAllText() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceBasic\ServiceResponse.cs:行号 98
   在 PWMIS.EnterpriseFramework.Service.Basic.ServiceResponse.get_AllText() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceBasic\ServiceResponse.cs:行号 41
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.Context_OnPublishDataEvent(Object sender, ServiceEventArgs e) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 570
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.PublishData(Object data) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 601
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceEventSource.DeActive() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceEventSource.cs:行号 75
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 33
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 589
------------------------------
[2017-12-18 18:18:41]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.Context_OnPublishDataEvent(Object sender, ServiceEventArgs e) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 569
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.PublishData(Object data) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 601
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceEventSource.DeActive() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceEventSource.cs:行号 75
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 33
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 589
------------------------------
[2017-12-18 18:21:23]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.Context_OnPublishDataEvent(Object sender, ServiceEventArgs e) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 571
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.PublishData(Object data) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 601
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceEventSource.DeActive() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceEventSource.cs:行号 75
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 33
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 589
------------------------------
[2017-12-18 18:21:48]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.Context_OnPublishDataEvent(Object sender, ServiceEventArgs e) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 569
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.PublishData(Object data) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 601
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceEventSource.DeActive() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceEventSource.cs:行号 75
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 33
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 589
------------------------------
[2017-12-18 18:22:22]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.Context_OnPublishDataEvent(Object sender, ServiceEventArgs e) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 571
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.PublishData(Object data) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 601
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceEventSource.DeActive() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceEventSource.cs:行号 75
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 33
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 589
------------------------------
[2017-12-18 18:26:18]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.Context_OnPublishDataEvent(Object sender, ServiceEventArgs e) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 570
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.PublishData(Object data) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 601
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceEventSource.DeActive() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceEventSource.cs:行号 75
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 33
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 589
------------------------------
[2017-12-19 11:12:57]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 595
------------------------------
[2017-12-19 11:22:03]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 595
------------------------------
[2017-12-19 11:22:58]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 595
------------------------------
[2017-12-19 11:50:15]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 595
------------------------------
[2017-12-19 11:53:51]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 595
------------------------------
[2017-12-19 12:05:32]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 595
------------------------------
[2017-12-19 12:06:29]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 595
------------------------------
[2017-12-19 12:06:51]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 595
------------------------------
[2017-12-19 12:07:31]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 595
------------------------------
[2017-12-19 12:08:11]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 595
------------------------------
[2017-12-19 12:09:12]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 595
------------------------------
[2017-12-19 12:12:25]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 595
------------------------------
[2017-12-19 12:13:58]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 595
------------------------------
[2017-12-19 12:14:30]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 595
------------------------------
[2017-12-19 12:14:34]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 595
------------------------------
[2017-12-19 13:21:55]处理服务的时候发生异常：执行服务方法错误：
源错误信息：sub error.，
请求的Uri:
Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:53570,WMI2114256838

错误发生时的异常对象调用堆栈：
System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 34
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 657
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2017-12-19 13:29:51]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass7_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 595
------------------------------
程序发生未处理的异常：
System.FormatException: 索引(从零开始)必须大于或等于零，且小于参数列表的大小。
   在 System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   在 System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   在 System.String.Format(String format, Object arg0, Object arg1)
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.Publish(String& workMessage) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 667
   在 PWMIS.EnterpriseFramework.Service.Host.ServicePublisher.DoEvent() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 326
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
------------------------------
程序发生未处理的异常：
System.InvalidCastException: 无法将类型为“PWMIS.EnterpriseFramework.Service.Host.NoneSessionServicePublisher”的对象强制转换为类型“PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher”。
   在 PWMIS.EnterpriseFramework.Service.Host.ServicePublisher.DoEvent() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 308
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
------------------------------
程序发生未处理的异常：
System.InvalidCastException: 无法将类型为“PWMIS.EnterpriseFramework.Service.Host.NoneSessionServicePublisher”的对象强制转换为类型“PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher”。
   在 PWMIS.EnterpriseFramework.Service.Host.ServicePublisher.DoEvent() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 308
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
------------------------------
程序发生未处理的异常：
System.InvalidCastException: 无法将类型为“PWMIS.EnterpriseFramework.Service.Host.NoneSessionServicePublisher”的对象强制转换为类型“PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher”。
   在 PWMIS.EnterpriseFramework.Service.Host.ServicePublisher.DoEvent() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 308
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
------------------------------
程序发生未处理的异常：
System.InvalidCastException: 无法将类型为“PWMIS.EnterpriseFramework.Service.Host.NoneSessionServicePublisher”的对象强制转换为类型“PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher”。
   在 PWMIS.EnterpriseFramework.Service.Host.ServicePublisher.DoEvent() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 308
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
------------------------------
程序发生未处理的异常：
System.InvalidCastException: 无法将类型为“PWMIS.EnterpriseFramework.Service.Host.NoneSessionServicePublisher”的对象强制转换为类型“PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher”。
   在 PWMIS.EnterpriseFramework.Service.Host.ServicePublisher.DoEvent() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 308
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
------------------------------
程序发生未处理的异常：
System.FormatException: 索引(从零开始)必须大于或等于零，且小于参数列表的大小。
   在 System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   在 System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   在 System.String.Format(String format, Object arg0, Object arg1)
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.Publish(String& workMessage) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 669
   在 PWMIS.EnterpriseFramework.Service.Host.ServicePublisher.DoEvent() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 328
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
------------------------------
程序发生未处理的异常：
System.FormatException: 索引(从零开始)必须大于或等于零，且小于参数列表的大小。
   在 System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   在 System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   在 System.String.Format(String format, Object arg0, Object arg1)
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.Publish(String& workMessage) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 669
   在 PWMIS.EnterpriseFramework.Service.Host.ServicePublisher.DoEvent() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 328
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
------------------------------
程序发生未处理的异常：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PWMIS.EnterpriseFramework.Service.Host.NoneSessionServicePublisher.Publish(String& workMessage) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 505
   在 PWMIS.EnterpriseFramework.Service.Host.ServicePublisher.DoWork() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 289
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
------------------------------
程序发生未处理的异常：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PWMIS.EnterpriseFramework.Service.Host.NoneSessionServicePublisher.Publish(String& workMessage) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 505
   在 PWMIS.EnterpriseFramework.Service.Host.ServicePublisher.DoWork() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 289
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
------------------------------
[2017-12-26 14:03:00]处理服务的时候发生异常：执行服务方法错误：
源错误信息：sub error.，
请求的Uri:
Service://Calculator/Sub/System.Int32=51&System.Int32=2，
127.0.0.1:59857,WMI2114256838

错误发生时的异常对象调用堆栈：
System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 34
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 657
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2017-12-26 14:20:45]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass6_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 604
------------------------------
[2017-12-26 15:19:57]处理服务的时候发生异常：事件源对象执行事件操作错误
错误发生时的异常对象调用堆栈：
System.Exception: test error...............
   在 ServiceSample.TestTimeService.PublishParallelData(Int32 timeCount) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 53
   在 ServiceSample.TestTimeService.<>c__DisplayClass4_0.<ParallelTime>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestTimeService.cs:行号 30
   在 PWMIS.EnterpriseFramework.Service.Host.EventServicePublisher.<>c__DisplayClass6_0.<Ready>b__0() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceHost\Publisher.cs:行号 604
------------------------------
[2018-07-30 15:32:43]处理服务的时候发生异常：执行服务方法错误：
源错误信息：sub error.，
请求的Uri:
Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:54538,WMI2114256838

错误发生时的异常对象调用堆栈：
System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 34
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 657
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2018-07-30 15:32:49]处理服务的时候发生异常：执行服务方法错误：
源错误信息：sub error.，
请求的Uri:
Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:54539,WMI2114256838

错误发生时的异常对象调用堆栈：
System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 34
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 657
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2018-07-30 15:33:00]处理服务的时候发生异常：执行服务方法错误：
源错误信息：sub error.，
请求的Uri:
Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:54541,WMI2114256838

错误发生时的异常对象调用堆栈：
System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 34
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 657
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2018-07-30 15:35:49]处理服务的时候发生异常：执行服务方法错误：
源错误信息：sub error.，
请求的Uri:
Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:54553,WMI2114256838

错误发生时的异常对象调用堆栈：
System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 34
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 657
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2018-07-30 15:37:40]处理服务的时候发生异常：执行服务方法错误：
源错误信息：当前方法调用无效，请确认方法名称正确并且具有公开的访问属性。，
请求的Uri:
Service://Calculator/Sub1/System.Int32=1&System.Int32=2，
127.0.0.1:54562,WMI2114256838

错误发生时的异常对象调用堆栈：
System.InvalidOperationException: 当前方法调用无效，请确认方法名称正确并且具有公开的访问属性。
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 656
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2018-07-30 15:39:15]处理服务的时候发生异常：执行服务方法错误：
源错误信息：当前方法调用无效，请确认方法名称正确并且具有公开的访问属性。，
请求的Uri:
Publish://AlarmClockService/SetAlarmTime1/System.DateTime=636685620060000000，
127.0.0.1:54572,WMI2114256838

错误发生时的异常对象调用堆栈：
System.InvalidOperationException: 当前方法调用无效，请确认方法名称正确并且具有公开的访问属性。
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 656
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2018-07-30 15:39:55]处理服务的时候发生异常：执行服务方法错误：
源错误信息：当前方法调用无效，请确认方法名称正确并且具有公开的访问属性。，
请求的Uri:
Publish://AlarmClockService/SetAlarmTime1/System.DateTime=636685619907960847，
127.0.0.1:54574,WMI2114256838

错误发生时的异常对象调用堆栈：
System.InvalidOperationException: 当前方法调用无效，请确认方法名称正确并且具有公开的访问属性。
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 656
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2018-07-30 15:41:18]处理服务的时候发生异常：执行服务方法错误：
源错误信息：当前方法调用无效，请确认方法名称正确并且具有公开的访问属性。，
请求的Uri:
Publish://AlarmClockService/SetAlarmTime1/System.DateTime=636685620757871177，
127.0.0.1:54577,WMI2114256838

错误发生时的异常对象调用堆栈：
System.InvalidOperationException: 当前方法调用无效，请确认方法名称正确并且具有公开的访问属性。
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 656
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2018-07-30 15:42:59]处理服务的时候发生异常：执行服务方法错误：
源错误信息：sub error.，
请求的Uri:
Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:54581,WMI2114256838

错误发生时的异常对象调用堆栈：
System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 34
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 657
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2018-07-30 15:48:06]处理服务的时候发生异常：执行服务方法错误：
源错误信息：sub error.，
请求的Uri:
Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:54597,WMI2114256838

错误发生时的异常对象调用堆栈：
System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 34
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 657
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2018-07-30 15:49:11]处理服务的时候发生异常：执行服务方法错误：
源错误信息：sub error.，
请求的Uri:
Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:54601,WMI2114256838

错误发生时的异常对象调用堆栈：
System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 34
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 657
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2018-07-30 15:49:52]处理服务的时候发生异常：执行服务方法错误：
源错误信息：sub error.，
请求的Uri:
Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:54605,WMI2114256838

错误发生时的异常对象调用堆栈：
System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 34
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 657
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2018-07-30 15:52:02]处理服务的时候发生异常：执行服务方法错误：
源错误信息：当前方法调用无效，请确认方法名称正确并且具有公开的访问属性。，
请求的Uri:
Publish://AlarmClockService/SetAlarmTime1/System.DateTime=636685627062387133，
127.0.0.1:54615,WMI2114256838

错误发生时的异常对象调用堆栈：
System.InvalidOperationException: 当前方法调用无效，请确认方法名称正确并且具有公开的访问属性。
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 656
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2018-07-30 16:05:41]处理服务的时候发生异常：执行服务方法错误：
源错误信息：当前方法调用无效，请确认方法名称正确并且具有公开的访问属性。，
请求的Uri:
Publish://AlarmClockService/SetAlarmTime1/System.DateTime=636685635363769554，
127.0.0.1:54640,WMI2114256838

错误发生时的异常对象调用堆栈：
System.InvalidOperationException: 当前方法调用无效，请确认方法名称正确并且具有公开的访问属性。
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 656
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474
------------------------------
[2018-07-30 16:08:46]处理服务的时候发生异常：执行服务方法错误：
源错误信息：sub error.，
请求的Uri:
Service://Calculator/Sub/System.Int32=1&System.Int32=2，
127.0.0.1:54654,WMI2114256838

错误发生时的异常对象调用堆栈：
System.Exception: sub error.
   在 ServiceSample.TestCalculatorService.Sub(Int32 a, Int32 b) 位置 E:\Git\sod\src\MessageServiceFramework\Test\Service\TestCalculatorService.cs:行号 34
   在 lambda_method(Closure , Object , Object[] )
   在 PWMIS.EnterpriseFramework.Service.Basic.DynamicMethodExecutor.Execute(Object instance, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceBasic\DynamicMethodExecutor.cs:行号 27
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.DynamicServiceCall(IService service, String methodName, Object[] parameters) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 657
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ExecuteService(IService service) 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 641
   在 PWMIS.EnterpriseFramework.Service.Runtime.ServiceContext.ProcessService() 位置 E:\Git\sod\src\MessageServiceFramework\PWMISServiceRuntime\ServiceContext.cs:行号 474